<p><span class="terms">DON'T SETTLE FOR 2ND BEST. ACCEPT NO SUBSTITUTES AND USE THE BEST SEX CONTACTS SERVICE. . . . .</span></p>
<p><span class="terms">WHATEVER YOU'RE INTO, however kinky you are.... Do we have something very special lined up for You....</span></p>
<p><span class="terms">IT'S NO SECRET that having more sex with more women is what life is all about.</span></p>
<p><span class="terms">WE'LL CHANGE YOUR MIND ABOUT using sex contacts by offering you the easiest quickest most convenient way t0o connect with a like-minded woman or women wherever you like in the UK - Anywhere in England, Wales, Northern Ireland &amp; of course Scotland.</span></p>
<p><span class="terms">IT'S A FACT OF LIFE THAT none us ever have enough sex with enough women, so here's where you start doing something really positive about it....</span></p>
<p><span class="terms">BEST OF ALL  - Whatever you're especially into, whatever most turns you on..... We can help you connect with a woman who's interested in the same sort of thing too.</span></p>
<p><span class="terms">BUT THAT'S JUST PART OF THE STORY -  with over 17,000 users at any one time, we can guarantee you success - Whether you're aged 18 or 50+, use us once, just once, and see what all the fuss is about, see why mobile telephone texting is the easiest quickiest most private and most effective way to make contact with a like-minded female.</span></p>
<p><span class="terms">To connect with a woman, wherever you live in Great Britain, who shares the same sex interests as you G-U-A-R-A-N-T-E-E-D - Follow the simple easy instructions below....</span></p>
<p><span class="terms">It's a piece of cake. NO. Actually - it's your sex dreams CUM TRUE...</span></p>
<br /><br />
<p><span class="termssmall"> Enjoy your sex life 1000000 more. Find horny fun the easy way, via your mobile phone. All women aged 18+. Enjoy your sex life much much much more. Get sex xxx with more personas more often. Find personas so you can fulfill your fantasies- You can do it, we can help 25p per text sent in to <?php echo SHORTCODE; ?> &amp; <?php echo PRICE; ?> per reply ( maximum 4 billed texts per reply). photos / videos sent /received - 2 x <?php echo PRICE; ?> (<?php echo TOTAL; ?>) You must be over 18 &amp; be the bill payer/have bill payers permission and to want to text for sexy times, absolutely no guarantee of meeting, for entertainment only. Remember you are responsible for paying your bill, Only spend what you can afford.. To stop service text stop to <?php echo SHORTCODE; ?> Photo &amp; data are for illustrative entertainment purposes. Guarantee is you'll receive a reply to your texts. by using the service you are confirming you have viewed and understood the full virtual service t+c's viewable at this website <?php echo $_SERVER['SERVER_NAME']; ?>. <?php echo ADDRESS; ?>. Enjoy your sex life much much more this year, check out some of these personas and fantasise 1000000 times more! Adults only 18+ service.</span></p>
